<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
        h3 {
            color: green;
        }
    </style>
</head>
<body>
<h1>Ссылка на регистрацию:</h1>
            <h3>ob6-intensive</h3>
<h2><a href="http://localhost:8080/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>
