<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Восстановление пароля</title>
    <style>
        h1 {
            color: cadetblue;
        }
        h2 {
            color: red;
        }
        h3 {
            color: green;
        }
    </style>
</head>
<body>
<h1>Ссылка для восстановления пароля:</h1>
<h3>ob6-intensive</h3>
<h2><a href="http://45.84.225.161/repass/${password_code}">Пройдите по ссылке для восстановления пароля</a></h2>
</body>
</html>